### PR TITLE
Command callbacks are called regardless of whether or not command fails

### PR DESCRIPTION
**Pull request by super-cooper**
**Description**
If a Command fails for whatever reason, there is nothing to communicate the outcome of the command and the callback is called regardless.

**To Reproduce**
1. Run `!poll`
2. Observe that the callback runs even though the command fails gracefully

**Expected behavior**
On command failure, the callback should be skipped. 

**Additional context**
We could maybe optionally allow a callback to run if commands fail under certain circumstances, but I can't imagine a scenario where regular cleanup in `Command.exec` would not suffice.

### CODE REVIEW

**Comment by super-cooper** [comment]
This one should be a pretty quick CR. The only thing I am iffy on is about our logging for a failed command. I wasn't sure if I should leave more of the detail work for when we add the logging system in the future.

**Comment by super-cooper** [comment]
Depends on #60

**Review by RobertWLeslie — DISMISSED** [review]
lg2m

**Comment by super-cooper** [comment]
This is still pending one review.

**Review by nhawke — DISMISSED** [review]

**Review by nhawke — APPROVED** [review]

**Review by RobertWLeslie — APPROVED** [review]
lgt2m

**Pull request merged**
