### PR TITLE
Create CommandOutput class so dicts/strings don't have to be hardcoded

### PR DESCRIPTION
**Pull request by super-cooper**
My thought process here is that hardcoding strings multiple times makes my skin crawl, and it also makes programmers less reliant on the documentation to determine what data they're allowed to send in a discord message. If you like it, cool.

### CODE REVIEW

**Comment by super-cooper** [comment]
> Hello @super-cooper! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:
> 
> * In the file [`commands.py`](https://github.com/super-cooper/memebot/blob/d4a236cb77c097a84b543680112ae14ed2834455/commands.py):
> 
> > [Line 23:80](https://github.com/super-cooper/memebot/blob/d4a236cb77c097a84b543680112ae14ed2834455/commands.py#L23): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (84 > 79 characters)
> > [Line 92:80](https://github.com/super-cooper/memebot/blob/d4a236cb77c097a84b543680112ae14ed2834455/commands.py#L92): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (97 > 79 characters)
> > [Line 98:80](https://github.com/super-cooper/memebot/blob/d4a236cb77c097a84b543680112ae14ed2834455/commands.py#L98): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (115 > 79 characters)
> > [Line 151:80](https://github.com/super-cooper/memebot/blob/d4a236cb77c097a84b543680112ae14ed2834455/commands.py#L151): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (88 > 79 characters)
> > [Line 179:80](https://github.com/super-cooper/memebot/blob/d4a236cb77c097a84b543680112ae14ed2834455/commands.py#L179): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (91 > 79 characters)
> > [Line 185:80](https://github.com/super-cooper/memebot/blob/d4a236cb77c097a84b543680112ae14ed2834455/commands.py#L185): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (82 > 79 characters)
> > [Line 189:80](https://github.com/super-cooper/memebot/blob/d4a236cb77c097a84b543680112ae14ed2834455/commands.py#L189): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (111 > 79 characters)
> > [Line 191:80](https://github.com/super-cooper/memebot/blob/d4a236cb77c097a84b543680112ae14ed2834455/commands.py#L191): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (90 > 79 characters)
> > [Line 194:80](https://github.com/super-cooper/memebot/blob/d4a236cb77c097a84b543680112ae14ed2834455/commands.py#L194): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (100 > 79 characters)
> > [Line 197:80](https://github.com/super-cooper/memebot/blob/d4a236cb77c097a84b543680112ae14ed2834455/commands.py#L197): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (87 > 79 characters)
> > [Line 199:80](https://github.com/super-cooper/memebot/blob/d4a236cb77c097a84b543680112ae14ed2834455/commands.py#L199): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (97 > 79 characters)
> > [Line 202:80](https://github.com/super-cooper/memebot/blob/d4a236cb77c097a84b543680112ae14ed2834455/commands.py#L202): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)
> > [Line 204:80](https://github.com/super-cooper/memebot/blob/d4a236cb77c097a84b543680112ae14ed2834455/commands.py#L204): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)
> > [Line 205:80](https://github.com/super-cooper/memebot/blob/d4a236cb77c097a84b543680112ae14ed2834455/commands.py#L205): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (119 > 79 characters)
> > [Line 207:80](https://github.com/super-cooper/memebot/blob/d4a236cb77c097a84b543680112ae14ed2834455/commands.py#L207): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (102 > 79 characters)
> > [Line 208:80](https://github.com/super-cooper/memebot/blob/d4a236cb77c097a84b543680112ae14ed2834455/commands.py#L208): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (86 > 79 characters)
> > [Line 217:80](https://github.com/super-cooper/memebot/blob/d4a236cb77c097a84b543680112ae14ed2834455/commands.py#L217): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (107 > 79 characters)
> > [Line 224:80](https://github.com/super-cooper/memebot/blob/d4a236cb77c097a84b543680112ae14ed2834455/commands.py#L224): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (80 > 79 characters)
> 
> * In the file [`memebot.py`](https://github.com/super-cooper/memebot/blob/d4a236cb77c097a84b543680112ae14ed2834455/memebot.py):
> 
> > [Line 37:80](https://github.com/super-cooper/memebot/blob/d4a236cb77c097a84b543680112ae14ed2834455/memebot.py#L37): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (100 > 79 characters)

Am I the only one who thinks 79 chars is a little (way) too short? I usually go with 120. Should I get rid of this PEP8 bot? lmao

**Comment by nhawke** [comment]
> Am I the only one who thinks 79 chars is a little (way) too short? I usually go with 120. Should I get rid of this PEP8 bot? lmao

I'm a fan of 79 chars because 80 is width of a terminal window by default (and some of us still like to code in terminal windows hehehe)

**Comment by super-cooper** [comment]
> > Am I the only one who thinks 79 chars is a little (way) too short? I usually go with 120. Should I get rid of this PEP8 bot? lmao
> 
> I'm a fan of 79 chars because 80 is width of a terminal window by default (and some of us still like to code in terminal windows hehehe)

\> Not making your terminal fullscreen

**Comment by nhawke** [comment]
> \> Not making your terminal fullscreen

\> not using vertical splits

**Pull request merged**
